// Code generated by "stringer -type=Endianness"; DO NOT EDIT.

package gq

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[BigEndian-0]
	_ = x[LittleEndian-1]
}

const _Endianness_name = "BigEndianLittleEndian"

var _Endianness_index = [...]uint8{0, 9, 21}

func (i Endianness) String() string {
	if i >= Endianness(len(_Endianness_index)-1) {
		return "Endianness(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Endianness_name[_Endianness_index[i]:_Endianness_index[i+1]]
}
