// Code generated by "stringer -type=QTypeID"; DO NOT EDIT.

package gq

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[QTypeID_KB-1]
	_ = x[QTypeID_UU-2]
	_ = x[QTypeID_KG-4]
	_ = x[QTypeID_KH-5]
	_ = x[QTypeID_KI-6]
	_ = x[QTypeID_KJ-7]
	_ = x[QTypeID_KE-8]
	_ = x[QTypeID_KF-9]
	_ = x[QTypeID_KC-10]
	_ = x[QTypeID_KS-11]
	_ = x[QTypeID_KP-12]
	_ = x[QTypeID_KM-13]
	_ = x[QTypeID_KD-14]
	_ = x[QTypeID_KN-16]
	_ = x[QTypeID_KU-17]
	_ = x[QTypeID_KV-18]
	_ = x[QTypeID_KT-19]
	_ = x[QTypeID_KZ-15]
	_ = x[QTypeID_XT-98]
	_ = x[QTypeID_XD-99]
	_ = x[QTypeID_ERROR - -128]
}

const (
	_QTypeID_name_0 = "QTypeID_ERROR"
	_QTypeID_name_1 = "QTypeID_KBQTypeID_UU"
	_QTypeID_name_2 = "QTypeID_KGQTypeID_KHQTypeID_KIQTypeID_KJQTypeID_KEQTypeID_KFQTypeID_KCQTypeID_KSQTypeID_KPQTypeID_KMQTypeID_KDQTypeID_KZQTypeID_KNQTypeID_KUQTypeID_KVQTypeID_KT"
	_QTypeID_name_3 = "QTypeID_XTQTypeID_XD"
)

var (
	_QTypeID_index_1 = [...]uint8{0, 10, 20}
	_QTypeID_index_2 = [...]uint8{0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120, 130, 140, 150, 160}
	_QTypeID_index_3 = [...]uint8{0, 10, 20}
)

func (i QTypeID) String() string {
	switch {
	case i == -128:
		return _QTypeID_name_0
	case 1 <= i && i <= 2:
		i -= 1
		return _QTypeID_name_1[_QTypeID_index_1[i]:_QTypeID_index_1[i+1]]
	case 4 <= i && i <= 19:
		i -= 4
		return _QTypeID_name_2[_QTypeID_index_2[i]:_QTypeID_index_2[i+1]]
	case 98 <= i && i <= 99:
		i -= 98
		return _QTypeID_name_3[_QTypeID_index_3[i]:_QTypeID_index_3[i+1]]
	default:
		return "QTypeID(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
